Output ace2king.gif

Set FontSize 12
Set Width 600
Set Height 600
Set FontFamily "Fira Code"
Set TypingSpeed 500ms

Type@100ms "go run cmd/scoreboard/*.go ben joe tina"

Enter

Sleep 500ms

Type "420"
Enter

Sleep 500ms

Down

Sleep 500ms

Down

Sleep 500ms

Type "69"
Enter

Sleep 500ms
Type "n"

Sleep 1s

Type "80"
Enter

Down


Sleep 500ms
Type "69"

Enter

Sleep 500ms
Type "n"

Sleep 3s
Type "q"